// DO NOT EDIT. This file is generated by fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import config from "./deno.json" assert { type: "json" };
import * as $0 from "./routes/about.tsx";
import * as $1 from "./routes/conferences.tsx";
import * as $2 from "./routes/cv.tsx";
import * as $3 from "./routes/index.tsx";
import * as $4 from "./routes/my-projects.tsx";
import * as $5 from "./routes/open-source.tsx";
import * as $6 from "./routes/tech-used.tsx";
import * as $$0 from "./islands/CollapseButton.tsx";

const manifest = {
  routes: {
    "./routes/about.tsx": $0,
    "./routes/conferences.tsx": $1,
    "./routes/cv.tsx": $2,
    "./routes/index.tsx": $3,
    "./routes/my-projects.tsx": $4,
    "./routes/open-source.tsx": $5,
    "./routes/tech-used.tsx": $6,
  },
  islands: {
    "./islands/CollapseButton.tsx": $$0,
  },
  baseUrl: import.meta.url,
  config,
};

export default manifest;
