name: fresh-update-dependencies

on:
  workflow_dispatch:
  schedule:
    - cron: "00 19 * * *"

jobs:
  update-dependencies:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x

      - name: Update dependencies
        run: |
          deno run -A -r https://fresh.deno.dev/update .

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        id: pr
        with:
          commit-message: "Fresh: Update dependencies"
          title: "Fresh: Update dependencies"
          body: >
            Automatic update of Deno fresh and its dependencies.
          branch: deno-dependency-updates
          author: GitHub <noreply@github.com>
          delete-branch: true
